### PR TITLE
Support for Buildroot 2024.02

### PR DESCRIPTION
**Pull request by kobayutapon**
Modified to work with Buildroot 2024.02.
- Changed Kernel to 6.1.x series.
- Fixed to start getty service when systemd is selected.
- Removed u-boot patch.

### CODE REVIEW

**Comment by petewasher-flybrid** [comment]
I tested this and it doesn't seem to work completely - build is ok, startup is OK. But when trying to install a rauc update I get the error below:
```
# rauc install rootfs.raucb
installing
  0% Installing
  0% Determining slot states
 10% Determining slot states done.
 10% Checking bundle
 10% Verifying signature
 20% Verifying signature done.
 20% Checking bundle done.
 20% Checking manifest contents
 30% Checking manifest contents done.
100% Installing failed.
LastError: Failed mounting bundle: Failed to open /dev/mapper/control: No such file or directory
Installing `/upload/rootfs.raucb` failed
```

Does this work on your setup?

**Comment by kobayutapon** [comment]
Sorry, I didn't check enough. I will check the symptoms you pointed out and send another pull request.

**Comment by petewasher-flybrid** [comment]
It seems we now need to specify all these items in `linux.fragment`:
```
CONFIG_MD=y
CONFIG_BLK_DEV_DM=y
CONFIG_BLK_DEV_LOOP=y
CONFIG_DM_VERITY=y
CONFIG_SQUASHFS=y
CONFIG_CRYPTO_SHA256=y
```

This is in line with the rauc docs: https://rauc.readthedocs.io/en/latest/integration.html#kernel-configuration

**Comment by kobayutapon** [comment]
I checked the operation and committed the fix.
Thanks for pointing this out.

**Comment by isius** [comment]
Readme.md:353 still references the u-boot patch removed by this.

**Comment by cdsteinkuehler** [comment]
README updated to indicate U-Boot now copies some of the device-tree nodes from the firmware loaded dtb to the live dtb.

**Pull request merged**
